language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t smurphy7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smurphy7/docker-react npm run test
